version: 2

models:
  - name: dim_listings_cleansed
    description: Cleansed table wich contains Airbnb listings.
    columns:

      - name: listing_id
        description: Unique identifier for each listing.
        tests:
          - unique
          - not_null

      - name: host_id
        description: Unique identifier for each host.
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: room_type
        description: The type of room the listing offers.
        tests:
          - accepted_values:
              values: [ 'Entire home/apt', 'Private room', 'Shared room', 'Hotel room' ]

      - name: minimum_nights
        description: '{{ doc("dim_listings_cleansed_minimum_nights") }}'
        tests:
          - positive_value

  - name: fct_reviews
    description: "The fct_reviews model is a transformation of the raw_reviews table from the AIRBNB schema. It includes the following columns: review_id, listing_id, review_date, reviewer_name, review_text, and review_sentiment. The review_id is a unique identifier generated using the MD5 hash function on a concatenation of the listing_id, review_date, reviewer_name, and review_text. The model filters out any records where the review_text is null."
  
  - name: dim_hosts_cleansed
    description: "The 'dim_hosts_cleansed' model is a transformation of the 'raw_hosts' table from the 'AIRBNB.raw' schema. It includes the following columns: 'host_id', 'host_name', 'is_superhost', 'created_at', and 'updated_at'. The 'host_name' column is coalesced with 'Anonymous' to handle null values. This model provides a cleansed and standardized view of the host data."
    columns:
      - name: host_id
        description: Unique identifier for each host. This is a primary key.
        data_type: number
      - name: host_name
        description: Name of the host. If the host name is not available, it is replaced with 'Anonymous'.
        data_type: varchar
      - name: is_superhost
        description: Boolean flag indicating whether the host is a superhost or not. Superhosts are experienced hosts who provide a shining example for other hosts, and extraordinary experiences for their guests.
        data_type: varchar
      - name: created_at
        description: The timestamp when the host record was first created in the Airbnb system.
        data_type: timestamp_ntz
      - name: updated_at
        description: The timestamp when the host record was last updated in the Airbnb system.
        data_type: timestamp_ntz

  - name: dim_listings_w_hosts
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('airbnb', 'listings')
    columns:
      - name: price
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 50
              max_value: 500
          - dbt_expectations.expect_column_max_to_be_between:
              max_value: 5000
              config:
                severity: warn
